<?php
namespace Aelia\WC;
if(!defined('ABSPATH')) exit; // Exit if accessed directly

if(!class_exists('Aelia\WC\Message')) {
	/**
	 * Class to represent messages generated by the plugin.
	 */
	class Message {
		public $level;
		public $code;
		public $message;

		/**
		 * Class constructor.
		 *
		 * @param int level The message level.
		 * @param string message The message itself.
		 * @param string code The message code, if any.
		 */
		public function __construct($level, $message, $code = '') {
			$this->level = $level;
			$this->message = $message;
			$this->code = $code;
		}
	}
}
